name: Impactifier 

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  extract-info:
    runs-on: ubuntu-latest

    outputs:
      branch_name: ${{ steps.extract.outputs.branch_name }}
      commit_sha: ${{ steps.extract.outputs.commit_sha }}
      pr_branch_name: ${{ steps.extract.outputs.pr_branch_name }}
      target_branch_name: ${{ steps.extract.outputs.target_branch_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Information
        id: extract
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            BRANCH_NAME=${{ github.ref_name }}
            COMMIT_SHA=${{ github.sha }}
            echo "branch_name=${BRANCH_NAME}" >> $GITHUB_ENV
            echo "commit_sha=${COMMIT_SHA}" >> $GITHUB_ENV
            echo "::set-output name=branch_name::$BRANCH_NAME"
            echo "::set-output name=commit_sha::$COMMIT_SHA"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_BRANCH_NAME=${{ github.head_ref }}
            TARGET_BRANCH_NAME=${{ github.base_ref }}
            echo "pr_branch_name=${PR_BRANCH_NAME}" >> $GITHUB_ENV
            echo "target_branch_name=${TARGET_BRANCH_NAME}" >> $GITHUB_ENV
            echo "::set-output name=pr_branch_name::$PR_BRANCH_NAME"
            echo "::set-output name=target_branch_name::$TARGET_BRANCH_NAME"
          fi
  run:
    runs-on: ubuntu-latest
    needs: extract-info
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run cli 
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            impactifier --from-branch ${{ needs.extract-info.outputs.branch_name }} --commit ${{ needs.extract-info.outputs.commit_sha }}
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            impactifier --from-branch ${{ needs.extract-info.outputs.pr_branch_name }} --to-branch ${{ needs.extract-info.outputs.target_branch_name }}
          fi

