repository:
  url: "https://github.com/wzslr321/impactifier"
options:
  clone_into: "./repo"

rules:
  - name: "Detect API Changes"
    trigger:
      path: "api/"
      pattern: "func (\\w+)Handler"
    transform:
      name: "toApiEndpoint"
      steps:
        - name: "toLowerCase"
        - name: "replace"
          args:
            pattern: "Handler$"
            with: "_endpoint"
        - name: "prepend"
          args:
            value: "/api/"
        - name: "customFunction"
          args:
            script: |
              fn transform(context) {
                  if context.class_name == "SpecialClass" {
                      return "/special" + context.matched_string;
                  } else {
                      return context.matched_string;
                  }
              }
    matcher:
      path: "client/"
      pattern: "ApiClient.call('$transform')"
    action:
      alert_level: "Severe"
      message: "API changed"
